---
- name: Gather yum and dnf command output
  hosts: all
  become: true
  tasks:
    - name: Check available updates using DNF
      command: dnf check-update
      register: dnf_check_update
      changed_when: false  # Task does not change system state
      failed_when: dnf_check_update.rc not in [0, 100]  # Avoid errors for non-zero return codes (e.g., no updates)
      tags: dnf_update_check

    - name: Display available updates (if any) from DNF
      debug:
        msg:
          - "DNF Check-Update Output:"
          - "{{ dnf_check_update.stdout_lines | default('No Output', true) }}"
      tags: dnf_update_check

    - name: Get Yum history
      command: yum history
      register: yum_history
      changed_when: false
      failed_when: yum_history.rc != 0
      tags: yum_history_check

    - name: Display Yum history
      debug:
        msg:
          - "YUM History Output:"
          - "{{ yum_history.stdout_lines | default('No Output', true) }}"
      tags: yum_history_check

    - name: Get Yum repository list
      command: yum repolist
      register: yum_repolist
      changed_when: false
      failed_when: yum_repolist.rc != 0
      tags: yum_repo_check

    - name: Display Yum repository list
      debug:
        msg:
          - "YUM Repo List:"
          - "{{ yum_repolist.stdout_lines | default('No Output', true) }}"
      tags: yum_repo_check

    - name: Get enabled Yum repositories
      command: yum repolist enabled
      register: yum_repolist_enabled
      changed_when: false
      failed_when: yum_repolist_enabled.rc != 0
      tags: yum_repo_enabled_check

    - name: Display enabled Yum repositories
      debug:
        msg:
          - "YUM Repo List (Enabled):"
          - "{{ yum_repolist_enabled.stdout_lines | default('No Output', true) }}"
      tags: yum_repo_enabled_check

    - name: Get disabled Yum repositories
      command: yum repolist disabled
      register: yum_repolist_disabled
      changed_when: false
      failed_when: yum_repolist_disabled.rc != 0
      tags: yum_repo_disabled_check

    - name: Display disabled Yum repositories
      debug:
        msg:
          - "YUM Repo List (Disabled):"
          - "{{ yum_repolist_disabled.stdout_lines | default('No Output', true) }}"
      tags: yum_repo_disabled_check

    - name: List installed packages using DNF
      command: dnf list installed
      register: dnf_list_installed
      changed_when: false
      failed_when: dnf_list_installed.rc != 0
      tags: dnf_list_installed

    - name: Display installed packages
      debug:
        msg:
          - "DNF List Installed Output:"
          - "{{ dnf_list_installed.stdout_lines | default('No Output', true) }}"
      tags: dnf_list_installed
