---
- name: Install Apache HTTPD on all servers
  hosts: all
  become: true
  tasks:
    - name: Ensure httpd is installed
      yum:
        name: httpd
        state: present

    - name: Ensure httpd service is started and enabled
      service:
        name: httpd
        state: started
        enabled: true
