---
- name: Check and apply updates on servers
  hosts: all
  become: yes
  tasks:
    
    - name: Check for available updates
      yum:
        list: updates
      register: updates_check

    - name: Display available updates
      debug:
        msg: "{{ updates_check.results }}"
    
    - name: Apply updates
      yum:
        name: '*'
        state: latest
      register: applied_updates

    - name: Display applied updates
      debug:
        msg: "{{ applied_updates.results | selectattr('state', 'equalto', 'updated') | map(attribute='name') | list }}"
    
    - name: List configured repositories
      command: yum repolist all
      register: repo_list

    - name: Display repository list
      debug:
        msg: "{{ repo_list.stdout_lines }}"
