---
- name: Display vm-user-activity.log file from remote servers
  hosts: all
  become: yes
  become_user: root
  tasks:
    - name: Show the contents of vm-user-activity.log
      command: cat /var/log/vm-user-activity.log
      register: log_content

    - name: Display log content
      debug:
        msg: "{{ log_content.stdout }}"
