---
- name: Read vm-user-activity.log
  hosts: srhel-1
  become: yes
  tasks:
    - name: Read the log file content
      command: cat /var/log/vm-user-activity.log
      register: log_content

    - name: Display log content
      debug:
        msg: "{{ log_content.stdout }}"
